### ISSUE TITLE
Possible to share the Dockerfile?

### ISSUE THREAD

**Issue by JohannesAck** [POSTECH-CVLab/PyTorch-StudioGAN#155]
Hi Minguk,

Thank you very much for posting these implementations, they are very helpful!

I am having some trouble running them in my own Docker container (some CUBLAS errors) so I then tried to use your container instead, however, with a size of 49GB, it is a bit too big for my available space.

Could you share the Dockerfile you used to build this container? I'm sure it would be very helpful to debug where the dependencies are different and to hopefully build a lighter container.

**Comment by alex4727** [comment]
Hi, we have replaced the outdated docker container image.
The container is now a lot more compact (17GB de-compressed) with updated frameworks installed. 
We'd love to share Dockerfile as well, but since we built our image manually on top of the PyTorch Docker image, we do not remember exact settings :(
If there's any problem you could try to manually install requirements as mentioned in ReadMe. 
Let me know if there's any problem
Thanks

**Comment by JohannesAck** [comment]
Thanks for updating the container!
