### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by zimonitrome** [POSTECH-CVLab/PyTorch-StudioGAN#41]
Is there any estimation on how long each GAN was trained?

A big hinder for layman training is compute. Listing times could indicate if a method is worth trying out. Other tips would be to implement FastGAN: https://github.com/odegeasslbc/FastGAN-pytorch

**Comment by MINGUKKANG** [comment]
Hi, 

Training GANs takes a lot of time, and it is one of the big hinders that prevent the layman from studying and training GANs.

Unfortunately, we do not plan to implement time-efficient GANs since the purpose of the repository is to compare widely used noise2pix GANs with each other. 

But, I will add details regarding time consumption on the README.

Thank you a lot!

**Comment by MINGUKKANG** [comment]
Close the issue.
