### ISSUE TITLE
What about pix2pix et al?

### ISSUE THREAD

**Issue by Rubiel1** [POSTECH-CVLab/PyTorch-StudioGAN#42]
Hi,
This looks like a great project.
I wonder why you don't have versions of Pix2pix, cycle-gan, etc.
Is there a copyright issue?

**Comment by MINGUKKANG** [comment]
Hi, 

Thank you so much for complimenting our repository.

We have not implemented pix2pix GANs since the purpose of the repository is to compare widely used noise2pix GANs with each other.

Implementing the Pix2Pix methods you suggested will be good.

However, we do not have enough time to do this sry:(
