### ISSUE TITLE
when num_classes*8 < batch_size, this should be a problem

### ISSUE THREAD

**Issue by youjiangxu** [POSTECH-CVLab/PyTorch-StudioGAN#43]
Hi,

https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/fff6c5b351fcdc35bedbfd0f5e5077090896be0a/src/utils/sample.py#L28

     when i visualized my model, it came out a bug as:

     the settinng is:
     the number of classes: 14
     the batch size is set to 256;

     Then the ``class_order_some'' sampler sample indices with `num_classes_plot = batch_size//8` (it should be 32).
     For the fake labels: I have only 14 classes, and `indices = np.random.permutation(num_classes)[:num_classes_plot]` only generates 14 indices.
     For the latent vector, it samples 256 vecs.
     It will generate batch_size mismatch as follow:
![image](https://user-images.githubusercontent.com/6999556/109658781-ee20a500-7ba1-11eb-9a1e-a9f019e6e346.png)

Best,
Youjiang Xu

**Comment by MINGUKKANG** [comment]
Hi,

Thank you for your bug reporting.

I identified the above problem and have fixed it. 

Instead of modifying the sample_latents function directly, I change the function named "define_sampler" located in src/utils/misc.py.

```python
def define_sampler(dataset_name, conditional_strategy, batch_size, num_classes):
     if conditional_strategy != "no":
         if dataset_name == "cifar10" or batch_size >= num_classes*8:
             sampler = "class_order_all"
         else:
             sampler = "class_order_some"
```

It will make StudioGAN visualize all classes in a single canvas when batch size is larger than num_class*8.

Thank you.

Best, 

MInguk

**Comment by ssabawissabawi** [comment]
Google
